import Head from 'next/head'
import { GetStaticPropsContext, InferGetStaticPropsType } from 'next'
import { trpc } from '~/utils/trpc'
import { getDictionary } from '~/dictionaries'


export default function Home({
  locale
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const hello = trpc.hello.useQuery({text: 'client'});
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        { hello.isLoading && <h1>Loading</h1>}
        { hello.isSuccess && <h1>{hello.data.greeting}</h1>}
        { locale.index.greeting }
      </main>
    </>
  )
}

export const getStaticProps = async ({ locale }: GetStaticPropsContext) => {
  return {
    props: {
      locale: await getDictionary(locale)
    }
  }
}